### ISSUE TITLE
social login with keycloak

### ISSUE THREAD

**Issue by r4nmaru1234** [owncloud/sociallogin#8]
Hello I want to setup Owncloud integration with keycloak but run into a couple of issues and cant find any guide or solutions so far

I have setup the keycloak and owncloud server and now i just have to make owncloud accept the keycloak login

Could someone give a few hints how the keycloak and owncloud configuration should look like? I tried several things but nothing seems to be working

Owncloud configuration

Authorize URL: http://10.2.1.27:8080/auth/realms/Patients/protocol/openid-connect/auth
Token URL: http://10.2.1.27:8080/auth/realms/Patients/protocol/openid-connect/token
User Info URL: http://10.2.1.27:8080/auth/realms/Patients/protocol/openid-connect/userinfo

![owncloud](https://user-images.githubusercontent.com/30414706/77235996-bc921200-6bba-11ea-9575-82594c31496d.png)

keycloak configuration settings
![keycloak settings](https://user-images.githubusercontent.com/30414706/77236000-cae02e00-6bba-11ea-9461-11bab9b669b1.png)

keycloak client scopes
![keycloak client scopes](https://user-images.githubusercontent.com/30414706/77236006-dc293a80-6bba-11ea-91cb-3cb6cf9066db.png)

error message
![error message](https://user-images.githubusercontent.com/30414706/77236055-26aab700-6bbb-11ea-81ce-2bcc35ec8607.png)

**Comment by DeepDiver1975** [comment]
I highly recommend using the openidconnect app which is about to be released these days.

We should archive sociallogin App ....

**Comment by r4nmaru1234** [comment]
thanks for the reply i was wondering why there was no further information on this app anymore
